name: "Gretting action"
description: "Une action simple"
inputs:
    username:
        description: "Username"
        required: true
    gretting:
        description: "gretting message to display"
        required: true
outputs:
    message:
        description: 'Le tag généré pour l’image Docker'
runs:
    using: "node20"
    main: "index.js"